services:
    app:
        build:
            args:
                # Não altere o nome de usuário abaixo
                user: dime
                uid: 1000
            context: ./
            dockerfile: docker/php/php.dockerfile
        image: php84
        extra_hosts:
            - host.docker.internal:host-gateway
        container_name: ${APP_NAME:-php}-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/.bashrc:/home/dime/.bashrc
            - ./docker/php/auth.json:/home/dime/.composer/auth.json
        networks:
            - dev

    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME:-web}-nginx
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - dev
        links:
            - app

#    swagger-ui:
#        image: swaggerapi/swagger-ui
#        ports:
#            - "8080:8080"
#        volumes:
#            - ./docs/api.yaml:/api.yaml
#        environment:
#            - SWAGGER_JSON=/api.yaml
#        networks:
#            - dev

    ############################
    # MySQL
    ############################
#    db:
#        image: mysql:latest
#        container_name: ${APP_NAME:-mysql}-db
#        restart: unless-stopped
#        environment:
#            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123456789}
#            MYSQL_DATABASE: ${DB_DATABASE:-skeleton}
#        ports:
#            - "${DB_PORT:-3306}:${DB_PORT:-3306}"
#        volumes:
#            - /home/${USUARIO:-dime}/mysqldb:/var/lib/mysql
#        networks:
#            - dev

    ############################
    # Postgres
    ############################
    db:
        image: postgres:16-alpine
        restart: unless-stopped
        container_name: ${APP_NAME:-postgres}-db
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-123456789}
        ports:
            - "${DB_PORT:-5432}:${DB_PORT:-5432}"
        volumes:
            - arquivos_postgres:/var/lib/postgresql/data
            - ./docker/postgres/01_estrutura_policia.sql:/docker-entrypoint-initdb.d/01_estrutura_policia.sql
            - ./docker/postgres/02_estrutura_seguranca.sql:/docker-entrypoint-initdb.d/02_estrutura_seguranca.sql
            - ./docker/postgres/03_dados.sql:/docker-entrypoint-initdb.d/03_dados.sql
        networks:
            - dev
volumes:
    arquivos_postgres:

networks:
    dev:
        driver: bridge
